# Tareas

**1) Diseñar nuestro modelo:** (input, output, size, forward pass)

**2) Construir "loss"(perdida) y "optimizer"(optimizador)**

**3) Bucle de entrenamiento:**
 - Forward pass: computar predicción
 - backward pass: gradientes
 - Actulizar los pesos 

In [3]:
import torch
import torch.nn as nn
from sklearn import linear_model

from sklearn import datasets

import numpy as np
import matplotlib.pyplot as plt

# Regresion lineal simple

## Datos

In [2]:
# Cargamos los datos de "datasets"
# X_numpy = Datos , y_numpy = Objetivo
X_numpy_simple, y_numpy_simple = datasets.make_regression(n_samples=100, n_features=1, n_targets=1, noise=25, random_state=1)

# Comvertimos los datos a tensores
X_simple = torch.from_numpy(X_numpy_simple.astype(np.float32))
y_simple = torch.from_numpy(y_numpy_simple.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna
y_simple = y_simple.view(y_simple.shape[0],1)

# Guardamos el numero de ejmplos y objentivos
#n_samples, n_features = X.shape

## Modelo

In [3]:
# Establecemos el numero de entradas de nuestro modelo
n_features = 1
# Establecemos el numero de salidas de nuestro modelo
output_size = 1

# Guardasmos nuesto modelo en "model"
model_Simple = nn.Linear(n_features, output_size)

## Entrenamiento

In [4]:
learning_rate = 0.05
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_Simple.parameters(), lr=learning_rate)

In [5]:
num_epocns = 100

for epoch in range(num_epocns):
    
    # Forward pass(pase hacia adelante)
    y_predicted = model_Simple(X_simple)
    
    # Loss(Perdida)
    loss = criterion(y_predicted, y_simple)
    
    # Backward pass(pase hacia atras)
    loss.backward()
    
    # Actulizacion
    optimizer.step()
    
    # Vover a 0 los gradientes
    optimizer.zero_grad()
    
    # Resultados
    if (epoch+1) % 10 == 0:
        print(f"epoch: {epoch+1}, loss = {loss.item():.4f}")

epoch: 10, loss = 1774.0710
epoch: 20, loss = 763.0552
epoch: 30, loss = 567.5303
epoch: 40, loss = 529.1401
epoch: 50, loss = 521.5320
epoch: 60, loss = 520.0159
epoch: 70, loss = 519.7128
epoch: 80, loss = 519.6521
epoch: 90, loss = 519.6398
epoch: 100, loss = 519.6375


# Regresion lineal múltiple

## Datos

In [12]:
# Cargamos los datos de "datasets"
# X_numpy = Datos , y_numpy = Objetivo
X_numpy_multi, y_numpy_multi = datasets.make_regression(n_samples=100, n_features=2, n_targets=1, noise=25, random_state=1)

# Comvertimos los datos a tensores
X_multi = torch.from_numpy(X_numpy_multi.astype(np.float32))
y_multi = torch.from_numpy(y_numpy_multi.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna
y_multi  = y_multi.view(y_multi.shape[0],1)

# Guardamos el numero de ejmplos y objentivos
#n_samples, n_features = X.shape

## Modelo

In [8]:
# Establecemos el numero de entradas de nuestro modelo
n_features = 2
# Establecemos el numero de salidas de nuestro modelo
output_size = 1

# Guardasmos nuesto modelo en "model"
model_Multiple = nn.Linear(n_features, output_size)

## Entrenamiento

In [9]:
learning_rate = 0.01
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_Multiple.parameters(), lr=learning_rate)

In [10]:
num_epocns = 100

for epoch in range(num_epocns):
    
    # Forward pass(pase hacia adelante)
    y_predicted = model_Multiple(X_multi)
    
    # Loss(Perdida)
    loss = criterion(y_predicted, y_multi)
    
    # Backward pass(pase hacia atras)
    loss.backward()
    
    # Actulizacion
    optimizer.step()
    
    # Vover a 0 los gradientes
    optimizer.zero_grad()
    
    # Resultados
    if (epoch+1) % 10 == 0:
        print(f"epoch: {epoch+1}, loss = {loss.item():.4f}")

epoch: 10, loss = 4643.9961
epoch: 20, loss = 3577.1201
epoch: 30, loss = 2813.2910
epoch: 40, loss = 2260.4126
epoch: 50, loss = 1856.1182
epoch: 60, loss = 1557.7010
epoch: 70, loss = 1335.5750
epoch: 80, loss = 1169.0015
epoch: 90, loss = 1043.2739
epoch: 100, loss = 947.8438


# Regresion multi variante

## Datos

In [21]:
# Cargamos los datos de "datasets"
# X_numpy = Datos , y_numpy = Objetivo
X_numpy_variante, y_numpy_variante = datasets.make_regression(n_samples=100, n_features=2, n_targets=2, noise=10, random_state=1)

# Comvertimos los datos a tensores
X_variante = torch.from_numpy(X_numpy_variante.astype(np.float32))
y_variante = torch.from_numpy(y_numpy_variante.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna
y_variante = y_variante.view(y_variante.shape[0],2)

# Guardamos el numero de ejmplos y objentivos
#n_samples, n_features = X.shape

## Modelo

In [25]:
#Establecemos el numero de entradas de nuestro modelo
n_features = 2
# Establecemos el numero de salidas de nuestro modelo
output_size = 2

# Guardasmos nuesto modelo en "model"
model_MultiVariente = nn.Linear(n_features, output_size)

## Entrenamiento

In [26]:
learning_rate = 0.1
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model_MultiVariente.parameters(), lr=learning_rate)

In [29]:
num_epocns = 100

for epoch in range(num_epocns):
    
    # Forward pass(pase hacia adelante)
    y_predicted = model_MultiVariente(X_variante)
    
    # Loss(Perdida)
    loss = criterion(y_predicted, y_variante)
    
    # Backward pass(pase hacia atras)
    loss.backward()
    
    # Actulizacion
    optimizer.step()
    
    # Vover a 0 los gradientes
    optimizer.zero_grad()
    
    # Resultados
    if (epoch+1) % 10 == 0:
        print(f"epoch: {epoch+1}, loss = {loss.item():.4f}")

epoch: 10, loss = 1488.3113
epoch: 20, loss = 443.4872
epoch: 30, loss = 193.7608
epoch: 40, loss = 129.4742
epoch: 50, loss = 112.2168
epoch: 60, loss = 107.4768
epoch: 70, loss = 106.1586
epoch: 80, loss = 105.7895
epoch: 90, loss = 105.6858
epoch: 100, loss = 105.6566


# Regresion lineal Lasso

## Datos

In [65]:
# Cargamos los datos de "datasets"
X_numpy_lasso, y_numpy_lasso = datasets.make_regression(n_samples=100, n_features=2, n_targets=2, noise=10, random_state=1)

# Comvertimos los datos a tensores
x_lasso = torch.from_numpy(X_numpy_lasso.astype(np.float32))
y_lasso = torch.from_numpy(y_numpy_lasso.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna

y_lasso = y_lasso.view(y_lasso.shape[0],2)

## Modelo

In [66]:
# Importamos y entrenamos nuestro modelo
clf = linear_model.Lasso(alpha=0.1)

## Testeo/ entrenamiento

In [67]:
# Importamos y entrenamos nuestro modelo
clf.fit(x_lasso, y_lasso)

# Medimos la puntucion de nuestro modelo
clf.score(x_lasso, y_lasso)

0.9725990637325824

# Regresión Bayesiana

## Datos

In [68]:
# Cargamos los datos de "datasets"
X_numpy_baye, y_numpy_baye = datasets.make_regression(n_samples=100, n_features=2, n_targets=1, noise=10, random_state=1)

# Comvertimos los datos a tensores
x_baye = torch.from_numpy(X_numpy_baye.astype(np.float32))
y_baye = torch.from_numpy(y_numpy_baye.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna

y_baye = y_baye.view(y_baye.shape[0],1)

## Modelo

In [69]:
# Importamos y entrenamos nuestro modelo
lb = linear_model.BayesianRidge()

## Testeo/ entrenamiento

In [70]:
# Importamos y entrenamos nuestro modelo
lb.fit(x_baye, y_baye)

# Medimos la puntucion de nuestro modelo
lb.score(x_baye,y_baye)

/home/monky/jupyter_dir/jupyter_env/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9818248431703536

# Regresión de Cresta

## Datos

In [71]:
# Cargamos los datos de "datasets"
X_numpy_ridge, y_numpy_ridge = datasets.make_regression(n_samples=100, n_features=2, n_targets=2, noise=10, random_state=1)

# Comvertimos los datos a tensores
x_ridge = torch.from_numpy(X_numpy_ridge.astype(np.float32))
y_ridge = torch.from_numpy(y_numpy_ridge.astype(np.float32))

# Cambiamos la forma de tensor "y" hacemos que el numero de valores sea 0(0==1) y que tenga una columna

y_ridge = y_ridge.view(y_ridge.shape[0],2)

## Modelo

In [72]:
# Importamos y entrenamos nuestro modelo
lr = linear_model.Ridge()

## Testeo/ entrenamiento

In [76]:
# Importamos y entrenamos nuestro modelo
lr.fit(x_ridge, y_ridge)

# Medimos la puntucion de nuestro modelo
print(lr.score(x_ridge,y_ridge))
print(lr.coef_)

-0.016124406551548454
[[9.99999264e-01 1.25978626e-06]
 [1.25978626e-06 9.99997425e-01]]


# Regresión Polinomial

## Datos

In [86]:
from sklearn.preprocessing import PolynomialFeatures

X_Poli = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_Poli = X[:, 0] ^ X[:, 1]

X_Poli = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)

## Modelo

In [88]:
# Importamos y entrenamos nuestro modelo
lp = linear_model.Perceptron(fit_intercept=False, max_iter=10, tol=None,shuffle=False)

## Testeo/ entrenamiento

In [89]:
# Importamos y entrenamos nuestro modelo
lp.fit(X_Poli, y_Poli)

# Medimos la puntucion de nuestro modelo
print(lp.score(X_Poli,y_Poli))
print(lp.coef_)

1.0
[[ 1.  1. -2.  0.  0. -2.  0.  0.  0.  0.  0.]]


In [4]:
######################## Librerias #########################
from sklearn import linear_model

from sklearn.preprocessing import PolynomialFeatures

import numpy as np

######################### Datos #########################
from sklearn.preprocessing import PolynomialFeatures

X_Poli = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_Poli = X_Poli[:, 0] ^ X_Poli[:, 1]

X_Poli = PolynomialFeatures(interaction_only=True).fit_transform(X_Poli).astype(int)

######################### Modelo/Entrenamiento/Testeo #########################
# Importamos y entrenamos nuestro modelo
lp = linear_model.Perceptron(fit_intercept=False, max_iter=10, tol=None,shuffle=False).fit(X_Poli, y_Poli)
# Medimos la puntucion de nuestro modelo
print(lp.score(X_Poli,y_Poli))
print(lp.coef_)

1.0
[[ 0.  2.  2. -5.]]
